version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  frontend:
    container_name: frontend
    restart: always
    build: ./client/
    ports:
      - "3000:3000"
    depends_on:
      - app
