version: "2"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27018:27017"
  backend:
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - ~/entryport/node-backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./client/
    ports:
      - "3000:3000"
    volumes:
      - ~/entryport/react-frontend:/usr/src/app
    depends_on:
      - backend
